name: jupyter_dashboards_workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - numpy
  - pylib
  - mpl_toolkits
